package com.cfgtest.services.customerservice.api.mappers;

import com.cfgtest.services.customerservice.dto.CustomerDTO;
import com.cfgtest.services.customerservice.model.Customer;
import org.mapstruct.Mapper;

// mapper annotation tell mapstruct processor to create an implementation of the below interface.
@Mapper(uses = DateMapper.class)
public interface CustomerMapper {

//    Autogenerated code will map Customer to CustomerDTO
//    @Mapping(source = <srcField> , target =  <destName>) can be used if the field names do not
//    match
    CustomerDTO convertToCustomerDTO(Customer customer);

    Customer convertToCustomer(CustomerDTO customerDTO);
}
